version: '3.8'

services:
  payment:
    build:
      context: .
    container_name: payment_service
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
    command: npm run start